/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2,the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four thousand, find the sum of the even-valued terms.
*/

#include <stdio.h>

int main(void)
{
    int n1 = 0; // You can also change to 0 as it doesn't add more to before
    int n2 = 1, n3 = 1;
    int sum = 0;

    while (1)
    {
        if (n1 >= 4000)
            break;

        printf("%d ", n1);

        if (n1 % 2 == 0)
            sum += n1;

        n2 = n1 + n3;
        n1 = n3;
        n3 = n2;
    }

    printf("\nSUM OF EVEN-VALUED TERMS: %d\n", sum);
}

/*
0 1 1 2 3 5 8 13 21 34 55 89 144 233 377 610 987 1597 2584
SUM OF EVEN-VALUED TERMS: 3382
*/
